# Generated by Django 3.2.5 on 2021-07-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RightTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Тег (права детей)',
                'verbose_name_plural': 'Теги (права детей)',
            },
        ),
        migrations.CreateModel(
            name='Right',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Право ребенка')),
                ('description', models.CharField(max_length=500, verbose_name='Описание права ребенка')),
                ('color', models.CharField(choices=[('#E9D379', 'Жёлтый'), ('#AAD59E', 'Зелёный'), ('#DF9687', 'Розовый'), ('#CDD2FA', 'Голубой')], default='#E9D379', max_length=8, verbose_name='Цвет фигуры')),
                ('text', models.TextField(null=True, verbose_name='1 текст права ребенка')),
                ('image_url', models.ImageField(blank=True, help_text='Добавить фото', upload_to='rights/', verbose_name='Фото')),
                ('tags', models.ManyToManyField(related_name='rights', to='rights.RightTag')),
            ],
            options={
                'verbose_name': 'Право ребенка',
                'verbose_name_plural': 'Права детей',
                'ordering': ['title', 'id'],
            },
        ),
    ]
