# Generated by Django 3.2.4 on 2021-06-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='tag',
            field=models.ManyToManyField(related_name='placetags', to='places.PlaceTag', verbose_name='Теги'),
        ),
    ]
