# Generated by Django 3.2.5 on 2021-07-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='tags',
            field=models.ManyToManyField(related_name='places', to='places.PlaceTag', verbose_name='Теги'),
        ),
    ]
