# Generated by Django 3.2.4 on 2021-06-24 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_place_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placetag',
            options={'verbose_name': 'Тег (места: куда пойти?)', 'verbose_name_plural': 'Теги (места: куда пойти?)'},
        ),
        migrations.RenameField(
            model_name='place',
            old_name='tag',
            new_name='tags',
        ),
    ]
