# Generated by Django 3.2.3 on 2021-06-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_tag'),
        ('places', '0002_alter_place_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='tag',
            field=models.ManyToManyField(blank=True, to='common.Tag', verbose_name='Тег'),
        ),
    ]
