# Generated by Django 3.2.3 on 2021-06-07 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_place_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='tag',
        ),
    ]
