# Generated by Django 3.2.4 on 2021-06-28 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('places', '0003_auto_20210624_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='common.city', verbose_name='Город'),
            preserve_default=False,
        ),
    ]
