# Generated by Django 3.2.4 on 2021-06-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_place_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Отображение на странице'),
        ),
    ]
