# Generated by Django 3.2.4 on 2021-07-01 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_place_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ('id',), 'verbose_name': 'Место - куда пойти?', 'verbose_name_plural': 'Места - куда пойти?'},
        ),
    ]
