# Generated by Django 3.2.5 on 2021-07-06 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_place_tags'),
        ('places', '0006_alter_place_options'),
    ]

    operations = [
    ]
