# Generated by Django 3.2.5 on 2021-07-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_rename_imageurl_place_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image_url',
            field=models.ImageField(help_text='Добавить фото', upload_to='places/', verbose_name='Фото'),
        ),
    ]
