# Generated by Django 3.2.5 on 2021-07-09 22:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_alter_place_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='age',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(40)], verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='place',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Опубликован'),
        ),
    ]
