# Generated by Django 3.2.5 on 2021-07-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_auto_20210709_2239'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='place',
            constraint=models.UniqueConstraint(fields=('title', 'address', 'city'), name='unique_place_for_city'),
        ),
    ]
