# Generated by Django 3.2.3 on 2021-05-24 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('mentor', 'Mentor'), ('moderator_regional', 'Moderator Reg'), ('moderator_general', 'Moderator Gen'), ('admin', 'Admin')], default='mentor', max_length=20, verbose_name='Роль'),
        ),
    ]
