# Generated by Django 3.2.3 on 2021-05-18 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_city_name'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='profile', to='common.city'),
        ),
    ]
