# Generated by Django 3.2.5 on 2021-07-05 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('female', 'женский'), ('male', 'мужской')], max_length=10)),
                ('email', models.EmailField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='curator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.curator', verbose_name='Куратор'),
            preserve_default=False,
        ),
    ]
