# Generated by Django 3.2.5 on 2021-07-05 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210705_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='curator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='users.curator', verbose_name='Куратор'),
        ),
    ]
