# Generated by Django 3.2.5 on 2021-07-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_curator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curator',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
