# Generated by Django 3.2.5 on 2021-07-05 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_curator_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curator',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='curator',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
