# Generated by Django 3.2.5 on 2021-07-05 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_curator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='curator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='users.curator', verbose_name='Куратор'),
        ),
    ]
