# Generated by Django 3.2.5 on 2021-07-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_curator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curator',
            options={'ordering': ('id',), 'verbose_name': 'Куратор', 'verbose_name_plural': 'Кураторы'},
        ),
        migrations.AlterField(
            model_name='curator',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='curator',
            name='gender',
            field=models.CharField(choices=[('female', 'женский'), ('male', 'мужской')], max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='curator',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
    ]
