# Generated by Django 3.2.4 on 2021-06-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(related_name='questiontags', to='questions.QuestionTag', verbose_name='Тэги'),
        ),
    ]
