# Generated by Django 3.2.5 on 2021-07-09 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.RenameField(
            model_name='question',
            old_name='pubDate',
            new_name='pub_date',
        ),
    ]
