# Generated by Django 3.2.4 on 2021-06-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_question_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questiontag',
            options={'ordering': ('-name',), 'verbose_name': 'Тег (вопросы)', 'verbose_name_plural': 'Теги (вопросы)'},
        ),
        migrations.AlterField(
            model_name='questiontag',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Адрес тега'),
        ),
    ]
