# Generated by Django 3.2.3 on 2021-06-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20210607_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tags', related_query_name='tags', to='questions.Tag'),
        ),
    ]
