# Generated by Django 3.2.3 on 2021-06-10 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20210607_2111'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='QuestionTag',
        ),
    ]
