# Generated by Django 3.2.3 on 2021-06-11 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_rename_tag_questiontag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='tag',
            new_name='tags',
        ),
    ]
