# Generated by Django 3.2.3 on 2021-05-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите город', max_length=30, verbose_name='Город')),
                ('isPrimary', models.BooleanField(default=False, help_text='Укажите, если город должен иметь приоритетный вывод', verbose_name='Приоритет вывода')),
                ('timeZone', models.CharField(choices=[('Europe/Kaliningrad', 'Калининград'), ('Europe/Moscow', 'Москва'), ('Europe/Kirov', 'Киров'), ('Europe/Volgograd', 'Волгоград'), ('Europe/Astrakhan', 'Астрахань'), ('Europe/Saratov', 'Саратов'), ('Europe/Ulyanovsk', 'Ульяновск'), ('Europe/Samara', 'Самара'), ('Asia/Yekaterinburg', 'Екатеринбург'), ('Asia/Omsk', 'Омск'), ('Asia/Novosibirsk', 'Новосибирск'), ('Asia/Barnaul', 'Барнаул'), ('Asia/Tomsk', 'Томск'), ('Asia/Novokuznetsk', 'Новокузнецк'), ('Asia/Krasnoyarsk', 'Красноярск'), ('Asia/Irkutsk', 'Иркутск'), ('Asia/Chita', 'Чита'), ('Asia/Yakutsk', 'Якутск'), ('Asia/Khandyga', 'Хандыга'), ('Asia/Vladivostok', 'Владивосток'), ('Asia/Ust-Nera', 'Усть-Нера'), ('Asia/Magadan', 'Магадан'), ('Asia/Sakhalin', 'Сахалин'), ('Asia/Srednekolymsk', 'Среднеколымск'), ('Asia/Kamchatka', 'Камчатка'), ('Asia/Anadyr', 'Анадырь')], default='Europe/Moscow', max_length=50, verbose_name='Часовой пояс')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
    ]
