# Generated by Django 3.2.4 on 2021-07-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите город', max_length=30, unique=True, verbose_name='Город')),
                ('isPrimary', models.BooleanField(default=False, help_text='Укажите, если город должен иметь приоритетный вывод', verbose_name='Приоритет вывода')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Загрузите фото', upload_to='meetings/', verbose_name='Фото')),
                ('description', models.TextField(help_text='Краткое описание', verbose_name='Описание')),
                ('smile', models.CharField(choices=[('sad', 'sad'), ('glad', 'glad'), ('normal', 'normal')], max_length=20)),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Встреча',
                'verbose_name_plural': 'Встречи',
                'ordering': ('-date',),
            },
        ),
    ]
