# Generated by Django 3.2.3 on 2021-05-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите город', max_length=30, unique=True, verbose_name='Город')),
                ('isPrimary', models.BooleanField(default=False, help_text='Укажите, если город должен иметь приоритетный вывод', verbose_name='Приоритет вывода')),
                ('timeZone', models.CharField(choices=[('Europe/Kaliningrad', 'Калининградское время GMT-1'), ('Europe/Moscow', 'Московское время GMT+0'), ('Europe/Samara', 'Самарское время GMT+1'), ('Asia/Yekaterinburg', 'Екатеринбургское время GMT+2'), ('Asia/Omsk', 'Омское время GMT+3'), ('Asia/Krasnoyarsk', 'Красноярское время GMT+4'), ('Asia/Irkutsk', 'Иркутское время GMT+5'), ('Asia/Yakutsk', 'Якутское время GMT+6'), ('Asia/Vladivostok', 'Владивостокское время GMT+7'), ('Asia/Srednekolymsk', 'Среднеколымское время GMT+8'), ('Asia/Kamchatka', 'Камчатское время GMT+9')], default='Europe/Moscow', max_length=50, verbose_name='Часовой пояс')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
    ]
