# Generated by Django 3.2.3 on 2021-05-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(help_text='Введите город', max_length=30, verbose_name='Город'),
        ),
    ]
