# Generated by Django 3.2.3 on 2021-05-26 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='isPrimary',
            new_name='is_primary',
        ),
    ]
