# Generated by Django 3.2.3 on 2021-05-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='timeZone',
            field=models.CharField(choices=[('Europe/Kaliningrad', 'Калининградское время GMT-1'), ('Europe/Moscow', 'Московское время GMT+0'), ('Europe/Samara', 'Самарское время GMT+1'), ('Asia/Yekaterinburg', 'Екатеринбургское время GMT+2'), ('Asia/Omsk', 'Омское время GMT+3'), ('Asia/Krasnoyarsk', 'Красноярское время GMT+4'), ('Asia/Irkutsk', 'Иркутское время GMT+5'), ('Asia/Yakutsk', 'Якутское время GMT+6'), ('Asia/Vladivostok', 'Владивостокское время GMT+7'), ('Asia/Srednekolymsk', 'Среднеколымское время GMT+8'), ('Asia/Kamchatka', 'Камчатское время GMT+9')], default='Europe/Moscow', max_length=50, verbose_name='Часовой пояс'),
        ),
    ]
