# Generated by Django 3.2.3 on 2021-06-07 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_remove_place_tag'),
        ('rights', '0002_remove_right_tag'),
        ('questions', '0004_auto_20210607_1903'),
        ('common', '0002_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.RemoveField(
            model_name='city',
            name='timeZone',
        ),
    ]
