# Generated by Django 3.2.3 on 2021-05-26 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_rename_isprimary_city_is_primary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='is_primary',
            new_name='isPrimary',
        ),
    ]
