# Generated by Django 3.2.5 on 2021-07-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20210701_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='place',
            field=models.CharField(max_length=200),
        ),
    ]
