# Generated by Django 3.2.5 on 2021-07-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_meeting_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='send_to_curator',
            field=models.BooleanField(default=False),
        ),
    ]
