# Generated by Django 3.2.5 on 2021-07-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_meeting_send_to_curator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='smile',
            field=models.CharField(choices=[('bad', 'bad'), ('good', 'good'), ('neutral', 'neutral')], max_length=20),
        ),
    ]
