# Generated by Django 3.2.5 on 2021-07-07 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_meeting_smile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='send_to_curator',
            new_name='sendToCurator',
        ),
    ]
