# Generated by Django 3.2.5 on 2021-07-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_rename_send_to_curator_meeting_sendtocurator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='sendToCurator',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
