# Generated by Django 3.2.5 on 2021-07-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_meeting_sendtocurator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='sendToCurator',
            field=models.BooleanField(default=False),
        ),
    ]
