# Generated by Django 3.2.5 on 2021-07-09 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_meeting_sendtocurator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='sendToCurator',
            new_name='send_to_curator',
        ),
    ]
