# Generated by Django 3.2.5 on 2021-07-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_rename_sendtocurator_meeting_send_to_curator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='description',
            field=models.TextField(help_text='Краткое описание', max_length=5000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='place',
            field=models.CharField(max_length=50),
        ),
    ]
