# Generated by Django 3.2.3 on 2021-06-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Right',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('text', models.TextField()),
                ('color', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('tag', models.ManyToManyField(to='common.Tag')),
            ],
        ),
    ]
