# Generated by Django 3.2.4 on 2021-06-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='right',
            name='tags',
            field=models.ManyToManyField(related_name='righttags', to='rights.RightTag'),
        ),
    ]
