# Generated by Django 3.2.4 on 2021-07-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='right',
            name='color',
        ),
        migrations.RemoveField(
            model_name='right',
            name='text',
        ),
        migrations.AddField(
            model_name='right',
            name='heading1',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок 1'),
        ),
        migrations.AddField(
            model_name='right',
            name='heading2',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок 2'),
        ),
        migrations.AddField(
            model_name='right',
            name='heading3',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок 3'),
        ),
        migrations.AddField(
            model_name='right',
            name='heading4',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок 4'),
        ),
        migrations.AddField(
            model_name='right',
            name='heading5',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок 5'),
        ),
        migrations.AddField(
            model_name='right',
            name='text1',
            field=models.TextField(null=True, verbose_name='1 текст права ребенка'),
        ),
        migrations.AddField(
            model_name='right',
            name='text2',
            field=models.TextField(null=True, verbose_name='2 текст права ребенка'),
        ),
        migrations.AddField(
            model_name='right',
            name='text3',
            field=models.TextField(null=True, verbose_name='3 текст права ребенка'),
        ),
        migrations.AddField(
            model_name='right',
            name='text4',
            field=models.TextField(null=True, verbose_name='4 текст права ребенка'),
        ),
        migrations.AddField(
            model_name='right',
            name='text5',
            field=models.TextField(null=True, verbose_name='5 текст права ребенка'),
        ),
    ]
