# Generated by Django 3.2.3 on 2021-06-12 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0002_auto_20210611_0054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='right',
            options={'ordering': ['title', 'id'], 'verbose_name': 'Право ребенка', 'verbose_name_plural': 'Права детей'},
        ),
        migrations.AlterModelOptions(
            name='righttag',
            options={'ordering': ['name', 'slug'], 'verbose_name': 'Тег (права детей)', 'verbose_name_plural': 'Теги (права детей)'},
        ),
    ]
