# Generated by Django 3.2.5 on 2021-07-07 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0002_auto_20210702_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='right',
            name='tags',
            field=models.ManyToManyField(related_name='rights', to='rights.RightTag'),
        ),
    ]
