# Generated by Django 3.2.5 on 2021-07-08 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0003_alter_right_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='righttag',
            options={'verbose_name': 'Тег (права детей)', 'verbose_name_plural': 'Теги (права детей)'},
        ),
    ]
