# Generated by Django 3.2.5 on 2021-07-09 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0004_alter_righttag_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='right',
            old_name='imageUrl',
            new_name='image_url',
        ),
    ]
