# Generated by Django 3.2.5 on 2021-07-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0005_rename_imageurl_right_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='right',
            old_name='text1',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='right',
            name='heading1',
        ),
        migrations.RemoveField(
            model_name='right',
            name='heading2',
        ),
        migrations.RemoveField(
            model_name='right',
            name='heading3',
        ),
        migrations.RemoveField(
            model_name='right',
            name='heading4',
        ),
        migrations.RemoveField(
            model_name='right',
            name='heading5',
        ),
        migrations.RemoveField(
            model_name='right',
            name='text2',
        ),
        migrations.RemoveField(
            model_name='right',
            name='text3',
        ),
        migrations.RemoveField(
            model_name='right',
            name='text4',
        ),
        migrations.RemoveField(
            model_name='right',
            name='text5',
        ),
        migrations.AddField(
            model_name='right',
            name='color',
            field=models.CharField(choices=[('#E9D379', 'Жёлтый'), ('#AAD59E', 'Зелёный'), ('#DF9687', 'Розовый'), ('#CDD2FA', 'Голубой')], default='#E9D379', max_length=8, verbose_name='Цвет фигуры'),
        ),
    ]
