# Generated by Django 3.2.5 on 2021-07-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(help_text='Поделитесь впечатлениями о проведенном времени', max_length=2000, verbose_name='Комментарий'),
        ),
    ]
