# Generated by Django 3.2.3 on 2021-06-06 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="main",
            options={
                "verbose_name": "Главная страница",
                "verbose_name_plural": "Главная страница",
            },
        ),
    ]
