# Generated by Django 3.2.4 on 2021-06-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0002_auto_20210629_2358'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='articles',
            field=models.ManyToManyField(to='entertainment.Article', verbose_name='Статьи(1 Верх, 2 Низ)'),
        ),
    ]
