# Generated by Django 3.2.4 on 2021-06-15 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
        ('questions', '0008_rename_tag_question_tags'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='place',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='places.place', verbose_name='Место - куда пойти?'),
        ),
        migrations.AlterField(
            model_name='main',
            name='questions',
            field=models.ManyToManyField(to='questions.Question', verbose_name='Вопросы'),
        ),
    ]
