# Generated by Django 3.2.3 on 2021-05-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_main_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='on_view',
            field=models.BooleanField(default=False, unique=True),
        ),
    ]
