# Generated by Django 3.2.4 on 2021-07-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='articles',
            field=models.ManyToManyField(to='entertainment.Article', verbose_name='Статьи'),
        ),
    ]
