# Generated by Django 3.2.5 on 2021-07-07 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0006_merge_20210707_1840'),
        ('story', '0002_auto_20210706_1900'),
        ('main', '0003_alter_main_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='history',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='story.story'),
        ),
        migrations.AddField(
            model_name='main',
            name='video',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='entertainment.video'),
        ),
    ]
