# Generated by Django 3.2.5 on 2021-07-07 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_auto_20210706_1900'),
        ('entertainment', '0010_alter_movietag_options'),
        ('main', '0004_auto_20210707_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='movies',
            field=models.ManyToManyField(to='entertainment.Movie', verbose_name='Фильмы'),
        ),
        migrations.AlterField(
            model_name='main',
            name='history',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='story.story', verbose_name='История'),
        ),
        migrations.AlterField(
            model_name='main',
            name='video',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='entertainment.video', verbose_name='Видео'),
        ),
    ]
