# Generated by Django 3.2.3 on 2021-05-26 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['startAt'], 'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='end_at',
            new_name='endAt',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_at',
            new_name='startAt',
        ),
    ]
