# Generated by Django 3.2.3 on 2021-05-26 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_rename_is_primary_city_isprimary'),
        ('afisha', '0002_auto_20210526_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='events', to='common.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='event',
            name='seats',
            field=models.PositiveIntegerField(verbose_name='Свободные места'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='eventparticipants', to='afisha.event', verbose_name='Мероприятие'),
        ),
    ]
