# Generated by Django 3.2.3 on 2021-05-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='seats',
            field=models.PositiveIntegerField(verbose_name='Свободные места'),
        ),
    ]
