# Generated by Django 3.2.5 on 2021-07-09 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='endAt',
            new_name='end_at',
        ),
    ]
