# Generated by Django 3.2.5 on 2021-07-09 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0003_auto_20210709_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='startAt',
            new_name='start_at',
        ),
    ]
