# Generated by Django 3.2.3 on 2021-05-26 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('afisha', '0003_auto_20210526_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipant',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventparticipants', to=settings.AUTH_USER_MODEL, verbose_name='Участник'),
        ),
    ]
