# Generated by Django 3.2.5 on 2021-07-06 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='stories/', verbose_name='Фотография')),
            ],
        ),
        migrations.AlterField(
            model_name='story',
            name='beginningOfFriendship',
            field=models.DateField(verbose_name='Дата начала дружбы'),
        ),
        migrations.DeleteModel(
            name='StoryImages',
        ),
        migrations.AddField(
            model_name='storyimage',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='story.story'),
        ),
    ]
