# Generated by Django 3.2.5 on 2021-07-08 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_auto_20210706_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='image',
            new_name='imageUrl',
        ),
    ]
