# Generated by Django 3.2.5 on 2021-07-09 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_rename_imageurl_story_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='pubDate',
            new_name='pub_date',
        ),
    ]
