# Generated by Django 3.2.5 on 2021-07-09 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_rename_pubdate_story_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ('-beginning_of_friendship',), 'verbose_name': 'История', 'verbose_name_plural': 'Истории'},
        ),
        migrations.RenameField(
            model_name='story',
            old_name='beginningOfFriendship',
            new_name='beginning_of_friendship',
        ),
    ]
