# Generated by Django 3.2.5 on 2021-07-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0006_auto_20210709_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=30, unique=True, verbose_name='Название истории'),
        ),
    ]
