# Generated by Django 3.2.5 on 2021-07-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0007_alter_story_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='passage',
            field=models.TextField(default=1, verbose_name='Цитата из текста'),
            preserve_default=False,
        ),
    ]
