# Generated by Django 3.2.5 on 2021-07-15 19:05

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основная статья')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название статьи')),
                ('author', models.CharField(max_length=200, verbose_name='Автор')),
                ('profession', models.CharField(max_length=200, verbose_name='Профессия')),
                ('description', models.TextField(verbose_name='Описание')),
                ('text', models.TextField(verbose_name='Текст')),
                ('color', colorfield.fields.ColorField(choices=[('#F8D162', 'yellow'), ('#8CDD94', 'green'), ('#FF8484', 'pink'), ('#C8D1FF', 'blue')], default='#FFFFFF', max_length=8, verbose_name='Цвет')),
                ('image_url', models.ImageField(blank=True, help_text='Добавить фото', upload_to='entertainment/articles/', verbose_name='Обложка')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BookTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название тега')),
                ('slug', models.SlugField(unique=True, verbose_name='Адрес тега')),
                ('color', colorfield.fields.ColorField(choices=[('#FF8484', 'red'), ('#C8D1FF', 'violet')], default='#FFFFFF', max_length=8, verbose_name='Цвет обложки на странице')),
            ],
            options={
                'verbose_name': 'Тег (Книга)',
                'verbose_name_plural': 'Теги (Книги)',
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название статьи')),
                ('description', models.CharField(max_length=500, verbose_name='Описание статьи')),
                ('image_caption', models.CharField(max_length=200, verbose_name='Описание к фотографии')),
                ('image_url', models.ImageField(blank=True, help_text='Добавить фото', upload_to='entertainment/guides/', verbose_name='Фото статьи')),
                ('text', models.TextField(verbose_name='Текст статьи')),
            ],
            options={
                'verbose_name': 'Статья справочника',
                'verbose_name_plural': 'Статьи справочника',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MovieTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, unique=True, verbose_name='Название тега')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Адрес тега')),
            ],
            options={
                'verbose_name': 'Тег (Фильмы)',
                'verbose_name_plural': 'Теги (Фильмы)',
            },
        ),
        migrations.CreateModel(
            name='VideoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название тега')),
                ('slug', models.SlugField(unique=True, verbose_name='Адрес тега')),
            ],
            options={
                'verbose_name': 'Тег (Видео)',
                'verbose_name_plural': 'Теги (Видео)',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=250, unique=True, verbose_name='Ссылка на видео')),
                ('title', models.CharField(blank=True, max_length=200, unique=True, verbose_name='Название видео')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='Автор')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('image_url', models.ImageField(blank=True, upload_to='entertainment/videos/', verbose_name='Картинка к видео')),
                ('creative_url', models.CharField(blank=True, max_length=250)),
                ('duration', models.DurationField(null=True, verbose_name='Продолжительность видео')),
                ('tags', models.ManyToManyField(related_name='videos', to='entertainment.VideoTag', verbose_name='Тэги')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=250, null=True, verbose_name='Ссылка на фильм')),
                ('title', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Название фильма')),
                ('producer', models.CharField(blank=True, max_length=255, verbose_name='Режиссер')),
                ('year', models.PositiveSmallIntegerField(blank=True, verbose_name='Год')),
                ('description', models.TextField(blank=True, verbose_name='Описание фильма')),
                ('image_url', models.ImageField(blank=True, upload_to='entertainment/movies/', verbose_name='Картинка к видео')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Продолжительность фильма')),
                ('tags', models.ManyToManyField(related_name='movies', to='entertainment.MovieTag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название книги')),
                ('author', models.CharField(max_length=200, verbose_name='Автор')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('description', models.TextField(verbose_name='Описание')),
                ('link', models.URLField(max_length=250, unique=True, verbose_name='Ссылка на книгу')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='entertainment.booktag', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['id'],
            },
        ),
    ]
