# Generated by Django 3.2.5 on 2021-07-14 21:00

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='color',
            field=colorfield.fields.ColorField(choices=[('#F8D162', 'yellow'), ('#8CDD94', 'green'), ('#FF8484', 'pink'), ('#C8D1FF', 'blue')], default='#FFFFFF', max_length=8, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='book',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='entertainment.booktag', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='booktag',
            name='color',
            field=colorfield.fields.ColorField(choices=[('#FF8484', 'red'), ('#C8D1FF', 'violet')], default='#FFFFFF', max_length=8, verbose_name='Цвет обложки на странице'),
        ),
    ]
