# Generated by Django 3.2.5 on 2021-07-16 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='link',
            field=models.URLField(default='ya.ru', unique=True, verbose_name='Ссылка на фильм'),
            preserve_default=False,
        ),
    ]
