# Generated by Django 3.2.5 on 2021-07-17 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0002_alter_movie_link'),
        ('entertainment', '0002_auto_20210717_0004'),
    ]

    operations = [
    ]
