# Generated by Django 3.2.5 on 2021-07-15 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(blank=True, help_text='Загрузите фото', upload_to='stories/', verbose_name='Фото')),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='Название истории')),
                ('beginning_of_friendship', models.DateField(verbose_name='Дата начала дружбы')),
                ('prolog', models.TextField(verbose_name='Пролог')),
                ('text', models.TextField(verbose_name='Текст истории')),
                ('passage', models.TextField(verbose_name='Цитата из текста')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'Истории',
                'ordering': ('-beginning_of_friendship',),
            },
        ),
        migrations.CreateModel(
            name='StoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='stories/', verbose_name='Фотография')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='story.story')),
            ],
        ),
    ]
