# Generated by Django 3.2.5 on 2021-07-14 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите город', max_length=30, unique=True, verbose_name='Город')),
                ('is_primary', models.BooleanField(default=False, help_text='Укажите, если город должен иметь приоритетный вывод', verbose_name='Приоритет вывода')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Загрузите фото', upload_to='meetings/', verbose_name='Фото')),
                ('description', models.TextField(help_text='Краткое описание', max_length=5000, verbose_name='Описание')),
                ('smile', models.CharField(choices=[('bad', 'bad'), ('good', 'good'), ('neutral', 'neutral')], max_length=20)),
                ('place', models.CharField(max_length=50)),
                ('date', models.DateField(blank=True, verbose_name='Дата')),
                ('send_to_curator', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to=settings.AUTH_USER_MODEL, verbose_name='Наставник')),
            ],
            options={
                'verbose_name': 'Встреча',
                'verbose_name_plural': 'Встречи',
                'ordering': ('-date',),
            },
        ),
    ]
