# Generated by Django 3.2.5 on 2021-07-14 00:22

from django.db import migrations

def set_default_cities(apps, schema_editor):
    City = apps.get_model('common', 'City')

    City.objects.create(name="Москва", is_primary=True)
    City.objects.create(name="Санкт-Петербург", is_primary=True)


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(set_default_cities),
    ]
