# Generated by Django 3.2.4 on 2021-07-01 12:03

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название статьи')),
                ('author', models.CharField(max_length=200, verbose_name='Автор')),
                ('profession', models.CharField(max_length=200, verbose_name='Профессия')),
                ('text', models.TextField(verbose_name='Описание')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18, verbose_name='Цвет обложки на странице')),
                ('imageUrl', models.ImageField(blank=True, help_text='Добавить фото', upload_to='entertainment/articles/', verbose_name='Обложка')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BookTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название тега')),
                ('slug', models.SlugField(unique=True, verbose_name='Адрес тега')),
            ],
            options={
                'verbose_name': 'Тег (Книга)',
                'verbose_name_plural': 'Теги (Книги)',
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название статьи')),
                ('description', models.CharField(max_length=500, verbose_name='Описание статьи')),
                ('imageCaption', models.CharField(max_length=200, verbose_name='Описание к фотографии')),
                ('imageUrl', models.ImageField(blank=True, help_text='Добавить фото', upload_to='entertainment/guides/', verbose_name='Фото статьи')),
                ('text', models.TextField(verbose_name='Текст статьи')),
            ],
            options={
                'verbose_name': 'Статья справочника',
                'verbose_name_plural': 'Статьи справочника',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MovieTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='VideoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название книги')),
                ('author', models.CharField(max_length=200, verbose_name='Автор')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('description', models.TextField(verbose_name='Описание')),
                ('tags', models.ManyToManyField(related_name='booktags', to='entertainment.BookTag')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['id'],
            },
        ),
    ]
