# Generated by Django 3.2.4 on 2021-06-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название статьи')),
                ('description', models.CharField(max_length=500, verbose_name='Описание статьи')),
                ('imageCaption', models.CharField(max_length=200, verbose_name='Описание к фотографии')),
                ('imageUrl', models.ImageField(blank=True, help_text='Добавить фото', upload_to='entertainment/manual/', verbose_name='Фото статьи')),
                ('text', models.TextField(verbose_name='Текст статьи')),
            ],
            options={
                'verbose_name': 'Справочник',
                'verbose_name_plural': 'Справочники',
                'ordering': ['-pk'],
            },
        ),
    ]
