# Generated by Django 3.2.4 on 2021-06-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booktag',
            options={'verbose_name': 'Тег (Книга)', 'verbose_name_plural': 'Теги (Книги)'},
        ),
        migrations.AlterField(
            model_name='guide',
            name='imageUrl',
            field=models.ImageField(blank=True, help_text='Добавить фото', upload_to='entertainment/guides/', verbose_name='Фото статьи'),
        ),
    ]
