# Generated by Django 3.2.4 on 2021-06-28 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manual',
            new_name='Guide',
        ),
        migrations.AlterModelOptions(
            name='guide',
            options={'ordering': ['-id'], 'verbose_name': 'Статья справочника', 'verbose_name_plural': 'Статьи справочника'},
        ),
    ]
