# Generated by Django 3.2.5 on 2021-07-09 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guide',
            old_name='imageCaption',
            new_name='image_caption',
        ),
    ]
