# Generated by Django 3.2.5 on 2021-07-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0002_auto_20210710_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='imageUrl',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Картинка к видео'),
        ),
    ]
