# Generated by Django 3.2.5 on 2021-07-06 17:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0002_alter_article_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['id'], 'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.AlterModelOptions(
            name='videotag',
            options={'verbose_name': 'Тег (Видео)', 'verbose_name_plural': 'Теги (Видео)'},
        ),
        migrations.AddField(
            model_name='video',
            name='author',
            field=models.CharField(default='', max_length=200, verbose_name='Автор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='link',
            field=models.CharField(default='', max_length=500, unique=True, verbose_name='Ссылка на видео'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='pubDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(related_name='videotags', to='entertainment.VideoTag'),
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default='', max_length=200, unique=True, verbose_name='Название видео'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videotag',
            name='name',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Название тега'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videotag',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='Адрес тега'),
            preserve_default=False,
        ),
    ]
