# Generated by Django 3.2.5 on 2021-07-09 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0003_auto_20210709_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='pubDate',
            new_name='pub_date',
        ),
    ]
