# Generated by Django 3.2.5 on 2021-07-06 20:05

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0003_auto_20210706_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18, verbose_name='Цвет обложки на странице'),
        ),
        migrations.AddField(
            model_name='book',
            name='link',
            field=models.URLField(max_length=250, unique=True, verbose_name='Ссылка на книгу'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.URLField(max_length=250, unique=True, verbose_name='Ссылка на видео'),
        ),
    ]
