# Generated by Django 3.2.5 on 2021-07-07 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0004_auto_20210707_0005'),
        ('entertainment', '0004_auto_20210707_1205'),
    ]

    operations = [
    ]
