# Generated by Django 3.2.5 on 2021-07-09 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0004_rename_pubdate_video_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='isMain',
            new_name='is_main',
        ),
    ]
