# Generated by Django 3.2.5 on 2021-07-06 20:29

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0004_auto_20210706_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=30, verbose_name='Цвет обложки на странице'),
        ),
        migrations.AlterField(
            model_name='book',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=30, verbose_name='Цвет обложки на странице'),
        ),
    ]
