# Generated by Django 3.2.5 on 2021-07-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0005_alter_video_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='imageUrl',
            field=models.URLField(blank=True, verbose_name='Картинка к видео'),
        ),
    ]
