# Generated by Django 3.2.5 on 2021-07-07 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0005_auto_20210706_2029'),
        ('entertainment', '0005_merge_0004_auto_20210707_0005_0004_auto_20210707_1205'),
    ]

    operations = [
    ]
