# Generated by Django 3.2.5 on 2021-07-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0006_alter_video_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='imageUrl',
            field=models.ImageField(blank=True, upload_to='entertainment/videos/', verbose_name='Картинка к видео'),
        ),
    ]
