# Generated by Django 3.2.5 on 2021-07-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0006_merge_20210707_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='isMain',
            field=models.BooleanField(default=False, verbose_name='Основная статья'),
        ),
    ]
