# Generated by Django 3.2.5 on 2021-07-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0007_video_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['id'], 'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AlterModelOptions(
            name='movietag',
            options={'ordering': ('-name',), 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание фильма'),
        ),
        migrations.AddField(
            model_name='movie',
            name='info',
            field=models.TextField(null=True, verbose_name='Информация о фильме'),
        ),
        migrations.AddField(
            model_name='movie',
            name='link',
            field=models.URLField(max_length=250, null=True, unique=True, verbose_name='Ссылка на фильм'),
        ),
        migrations.AddField(
            model_name='movie',
            name='preview',
            field=models.ImageField(blank=True, upload_to='entertainment/movies/', verbose_name='Картинка к фильму'),
        ),
        migrations.AddField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(related_name='movies', to='entertainment.MovieTag', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Название фильма'),
        ),
        migrations.AddField(
            model_name='movietag',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Название тега'),
        ),
        migrations.AddField(
            model_name='movietag',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='Адрес тега'),
        ),
        migrations.AddField(
            model_name='video',
            name='preview',
            field=models.ImageField(blank=True, upload_to='entertainment/videos/', verbose_name='Картинка к видео'),
        ),
    ]
