# Generated by Django 3.2.5 on 2021-07-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0007_alter_video_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='creative_url',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
