# Generated by Django 3.2.5 on 2021-07-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0008_video_creative_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='imageUrl',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='pub_date',
            new_name='pubDate',
        ),
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(related_name='videos', to='entertainment.VideoTag', verbose_name='Тэги'),
        ),
    ]
