# Generated by Django 3.2.5 on 2021-07-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0008_auto_20210707_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.DurationField(null=True, verbose_name='Продолжительность фильма'),
        ),
    ]
