# Generated by Django 3.2.5 on 2021-07-07 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0009_movie_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movietag',
            options={'ordering': ('-name',), 'verbose_name': 'Тег (Фильмы)', 'verbose_name_plural': 'Теги (Фильмы)'},
        ),
    ]
