# Generated by Django 3.2.5 on 2021-07-13 20:15

import colorfield.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0010_rename_pubdate_video_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='color',
        ),
        migrations.AddField(
            model_name='booktag',
            name='color',
            field=colorfield.fields.ColorField(choices=[('#FC8585', 'red'), ('#C8D1FF', 'violet')], default='#FFFFFF', max_length=30, verbose_name='Цвет обложки на странице'),
        ),
        migrations.AlterField(
            model_name='article',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18, verbose_name='Цвет обложки на странице'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание фильма'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image_url',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to='entertainment/movies/', verbose_name='Картинка к видео'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='producer',
            field=models.CharField(blank=True, max_length=255, verbose_name='Режиссер'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Название фильма'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Год'),
        ),
    ]
