# Generated by Django 3.2.5 on 2021-07-13 20:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0011_auto_20210713_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='tags',
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='entertainment.booktag'),
            preserve_default=False,
        ),
    ]
