# Generated by Django 3.2.5 on 2021-07-13 23:12

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0013_rename_tags_book_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='color',
            field=colorfield.fields.ColorField(choices=[('#E9D379', 'yellow'), ('#AAD59E', 'green'), ('#DF9687', 'pink'), ('#CDD2FA', 'blue')], default='#FFFFFF', max_length=8, verbose_name='Цвет обложки на странице'),
        ),
        migrations.AlterField(
            model_name='booktag',
            name='color',
            field=colorfield.fields.ColorField(choices=[('#FC8585', 'red'), ('#C8D1FF', 'violet')], default='#FFFFFF', max_length=8, verbose_name='Цвет обложки на странице'),
        ),
    ]
